language: php

notifications:
  email:
    on_success: never
    on_failure: change

# Declare versions of PHP to use. Use one decimal max.
matrix:
  include:
  - php: 7.1
  - php: 5.4
  - php: 5.3
    dist: precise

# Declare which versions of WordPress to test against.
# Also declare whether or not to test in Multisite.
env:
    # Trunk (current version in development is 4.7)
    # @link https://github.com/WordPress/WordPress
    - WP_VERSION=master WP_MULTISITE=0

before_script:
  - yarn install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
